name: neuralangelo-dtu-wmask-dtu_scan24
tag: ''
seed: 42
dataset:
  name: dtu
  root_dir: ./load/DTU-neus/dtu_scan24
  cameras_file: cameras_sphere.npz
  img_downscale: 2
  n_test_traj_steps: 60
  apply_mask: true
model:
  name: neus
  radius: 1.0
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 2048
  cos_anneal_end: 20000
  learned_background: false
  background_color: white
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: adaptive-volume-sdf
    radius: 1.0
    feature_dim: 13
    grad_type: finite_difference
    finite_difference_eps: progressive
    isosurface:
      method: mc
      resolution: 612
      chunk: 2097152
      threshold: 0.0
    xyz_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
      adaptive: true
      start_level: 8
      start_step: 0
      update_steps: 500
    spatial_filter_config:
      name: volume-density
      radius: 1.0
      feature_dim: 32
      isosurface:
        method: mc
        resolution: 256
        chunk: 2097152
        threshold: 5.0
      xyz_encoding_config:
        otype: HashGrid
        n_levels: 12
        n_features_per_level: 2
        log2_hashmap_size: 19
        base_resolution: 32
        per_level_scale: 1.3195079107728942
        include_xyz: true
      mlp_network_config:
        otype: VanillaMLP
        activation: ReLU
        output_activation: sigmoid
        n_neurons: 64
        n_hidden_layers: 1
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
  texture:
    name: volume-radiance
    input_feature_dim: 16
    dir_encoding_config:
      n_dir_dims: 3
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
system:
  name: neus-system
  loss:
    lambda_rgb_mse: 0.0
    lambda_rgb_l1: 1.0
    lambda_mask: 0.1
    lambda_eikonal: 0.1
    lambda_L1_frequency: 0.00035
    lambda_curvature: 0.0
    lambda_sparsity: 0.0
    lambda_distortion: 0.0
    lambda_distortion_bg: 0.0
    lambda_opaque: 0.0
    sparsity_scale: 1.0
    frequency_loss_fade_end : 1500
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas:
      - 0.9
      - 0.99
      eps: 1.0e-15
    params:
      geometry:
        spatialfilter:
          lr: 0.0005
        lr: 0.01
      texture:
        lr: 0.01
      variance:
        lr: 0.001
  constant_steps: 5000
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
    - 5000
    schedulers:
    - name: ConstantLR
      args:
        factor: 1.0
        total_iters: 5000
    - name: ExponentialLR
      args:
        gamma: 0.9998465061085267
checkpoint:
  save_top_k: -1
  every_n_train_steps: 20000
export:
  chunk_size: 2097152
  export_vertex_color: true
trainer:
  max_steps: 20000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 500
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true
  precision: 16
